[package]
name = "fractal_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.8.2"
num-complex = "0.4.3"
pixel-canvas = "0.2.3"
rand = "0.8.5"
rayon = "1.6.1"
rust-gpu = "0.1.0"
