on: push

name: Build and test

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Build
        run: cargo build --release --all-features
      - name: Test
        run: cargo test --release --all-features
      - name: Clean
        run: cargo clean
#       - name: Build Wasm
#         run: trunk build --release

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt --all -- --check